[build]
  # ビルドコマンドと公開ディレクトリ
  base = "nuxt-app/"
  command = "npm install && npm run build"
  publish = ".output/public"
  functions = ".output/server"

[build.environment]
  # Node.jsバージョン指定
  NODE_VERSION = "18"

# Nuxt3の環境変数
[context.production.environment]
  NITRO_PRESET = "netlify"

# API routes
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/server"
  status = 200

# Dynamic routes
[[redirects]]
  from = "/*"
  to = "/.netlify/functions/server"
  status = 200

# ヘッダー設定
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"
    X-XSS-Protection = "1; mode=block"